export const HANDLE_INPUT_TOOL = 'HANDLE_INPUT_TOOL';
export const INIT_BATCH_TOOL = 'INIT_BATCH_TOOL';

export const CHECK_ADDR_IS_CONTRACT = 'CHECK_ADDR_IS_CONTRACT';

export const VALIDATE_BEGIN = 'VALIDATE_BEGIN';

export const ERC_165_CHECK = 'ERC_165_CHECK';
export const ERC_721_CHECK = 'ERC_721_CHECK';
export const ERC_1155_CHECK = 'ERC_1155_CHECK';

export const ERC_721_METADATA_CHECK = 'ERC_721_METADATA_CHECK';
export const ERC_721_ENUMERABLE_CHECK = 'ERC_721_ENUMERABLE_CHECK';
export const ERC_721_NAME_CHECK = 'ERC_721_NAME_CHECK';
export const ERC_721_SYMBOL_CHECK = 'ERC_721_SYMBOL_CHECK';
export const ERC_721_TOTAL_SUPPLY_CHECK = 'ERC_721_TOTAL_SUPPLY_CHECK';
export const ERC_721_TOKEN_BY_INDEX_CHECK = 'ERC_721_TOKEN_BY_INDEX_CHECK';
export const ERC_721_TOKEN_OF_OWNER_BY_INDEX_CHECK =
  'ERC_721_TOKEN_OF_OWNER_BY_INDEX_CHECK';
export const ERC_721_TOKENURI_CHECK = 'ERC_721_TOKENURI_CHECK';

export const ERC_1155_TOKENURI_CHECK = 'ERC_1155_TOKENURI_CHECK';

export const TOKEN_METADATA_CHECK = 'TOKEN_METADATA_CHECK';

export const REFRESH = 'REFRESH';

export const BLOCK_ERC721_CHECK = 'BLOCK_ERC721_CHECK';
export const BLOCK_ERC1155_CHECK = 'BLOCK_ERC1155_CHECK';
